title: スクロールアニメーション02
label: スクロールアニメーション02
variants:
  - name: default
    label: スクロールアニメーション02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  img: 'https://picsum.photos/id/237/200/300'
