title: ボタン24
label: ボタン24
variants:
  - name: default
    label: ボタン24
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  text: 'BUTTON24'
