title: その他10
label: その他10
variants:
  - name: default
    label: その他10
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-plain'
context:
  img: 'https://picsum.photos/id/1000/400/200'
  link: '#'
  date: '2021.00.00'
  thumb: 'https://picsum.photos/id/1001/400/200'
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
