title: 表組データ並び替え
label: 表組データ並び替え
variants:
  - name: default
    label: 汎用パーツ09
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
