title: 汎用パーツ09
label: 汎用パーツ09
variants:
  - name: default
    label: 汎用パーツ09
    # status: ready
    # status: prototype
    status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
