title: スクロールアニメーション12
label: スクロールアニメーション12
variants:
  - name: default
    label: スクロールアニメーション12
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  heading1: 'SCROLL'
  heading2: 'ANIMATION'
