title: よくある質問04
label: よくある質問04
variants:
  - name: default
    label: よくある質問04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  faqItems:
    - question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
