title: カウントダウンタイマー
label: カウントダウンタイマー
variants:
  - name: default
    label: 汎用パーツ08
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
