title: スクロールアニメーション25
label: スクロールアニメーション25
variants:
  - name: default
    label: スクロールアニメーション25
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  items:
    - percent: 80
    - percent: 96
    - percent: 75
