title: カード21
label: カード21
variants:
  - name: default
    label: カード21
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  heads:
    - 見出し
    - 長い見出し長い見出し長い見出し長い見出し
    - 見出し
    - 見出し
    - 見出し
    - 長い見出し長い見出し長い見出し長い見出し長い見出し長い見出し
    - 見出し
    - 見出し
    - 長い見出し長い見出し長い見出し長い見出し
    - 長い見出し長い見出し長い見出し
  texts:
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
    - テキストが入ります。テキストが入ります。テキストが入ります。
