title: スクロールアニメーション29
label: スクロールアニメーション29
variants:
  - name: default
    label: スクロールアニメーション29
    status: ready
    # status: prototype
    # status: wip
# hidden: true
preview: '@preview-scroll'
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
