title: スクロールアニメーション23
label: スクロールアニメーション23
variants:
  - name: default
    label: スクロールアニメーション23
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  items:
    - heading: '見出し01'
      content: 'テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
      img: 'https://picsum.photos/id/1000/400/400'
      spImg: 'https://picsum.photos/id/1000/400/200'
    - heading: '見出し02'
      content: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
      img: 'https://picsum.photos/id/1001/400/400'
      spImg: 'https://picsum.photos/id/1001/400/200'
    - heading: '見出し03'
      content: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
      img: 'https://picsum.photos/id/1002/400/400'
      spImg: 'https://picsum.photos/id/1002/400/200'
    - heading: '見出し04'
      content: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
      img: 'https://picsum.photos/id/1003/400/400'
      spImg: 'https://picsum.photos/id/1003/400/200'
    - heading: '見出し05'
      content: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
      img: 'https://picsum.photos/id/1004/400/400'
      spImg: 'https://picsum.photos/id/1004/400/200'
