title: カード12
label: カード12
variants:
  - name: default
    label: カード12
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - link: '#'
      img: 'https://picsum.photos/id/1000/400/200'
      category: 'NEWS'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
      date: '2021.01.01'
    - link: '#'
      img: 'https://picsum.photos/id/1000/400/200'
      category: 'NEWS'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
      date: '2021.01.01'
    - link: '#'
      img: 'https://picsum.photos/id/1000/400/200'
      category: 'NEWS'
      text: 'テキストが入ります。テキストが入ります。'
      date: '2021.01.01'
