title: スクロールアニメーション22
label: スクロールアニメーション22
variants:
  - name: default
    label: スクロールアニメーション22
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  items:
    - job: '職種01'
      company: '企業名01'
      term: '2015/00 - 2016/00'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - job: '職種02'
      company: '企業名02'
      term: '2016/00 - 2017/00'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - job: '職種03'
      company: '企業名03'
      term: '2017/00 - 2018/00'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
