title: ニュース一覧04
label: ニュース一覧04
variants:
  - name: default
    label: ニュース一覧04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - link: '#'
      date: '2021.01.01'
      category: 'お知らせ'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      date: '2021.01.02'
      category: 'メディア'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      date: '2021.01.03'
      category: 'お知らせ'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
