title: カード06
label: カード06
variants:
  - name: default
    label: カード06
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: https://picsum.photos/400/200
  date: 2020.10.01
  category: お知らせ
  title: タイトルが入ります
  text: テキストが入ります。テキストが入ります。テキストが入ります。
