title: サービス一覧04
label: サービス一覧04
variants:
  - name: default
    label: サービス一覧04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://bonx.co.jp/wp-content/themes/bonxwork_ver.1.0/common/images/features__icon--cost.svg'
  title: 'タイトルが入ります'
  copy: 'キャッチコピーが入ります。キャッチコピーが入ります。'
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
