title: スクロールアニメーション03
label: スクロールアニメーション03
variants:
  - name: default
    label: スクロールアニメーション03
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  text: 'スクロールアニメーション03'
