title: 注文フォーム
label: 注文フォーム
variants:
  - name: default
    label: 汎用パーツ06
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
