title: クッキー情報取得確認
label: クッキー情報取得確認
variants:
  - name: default
    label: 汎用パーツ01
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
