title: カード15
label: カード15
variants:
  - name: default
    label: カード15
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://picsum.photos/id/1000/400/400'
  heading: '見出しが入ります見出しが入ります見出しが入ります'
  category: 'カテゴリー'
  date: '2021/00/00'
