title: スクロールアニメーション09
label: スクロールアニメーション09
variants:
  - name: default
    label: スクロールアニメーション09
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  text: 'テキストが入ります。テキストが入ります。<br>テキストが入ります。'
