title: ボタン10
label: ボタン10
variants:
  - name: default
    label: ボタン10
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  text: ボタン10
  textEn: Button10
