title: カード11
label: カード11
variants:
  - name: default
    label: カード11
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://picsum.photos/400/200'
  title: 'カード00'
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
  date: '2021.01.01'
