title: ニュース一覧06
label: ニュース一覧06
variants:
  - name: default
    label: ニュース一覧06
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - link: '#'
      date: '2021.01.03'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      date: '2021.01.02'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      date: '2021.01.01'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
