title: カード04
label: カード04
variants:
  - name: default
    label: カード04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: https://picsum.photos/400/200
  title: タイトルが入ります。タイトルが入ります。
  text: テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。
