title: スクロールアニメーション00
label: スクロールアニメーション00
variants:
  - name: default
    label: スクロールアニメーション00
    status: ready
    # status: prototype
    # status: wip
# hidden: true
preview: '@preview-scroll'
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
