title: カード05
label: カード05
variants:
  - name: default
    label: カード05
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://picsum.photos/400/200'
  width: 400
  height: 200
