title: ギャラリー01
label: ギャラリー01
variants:
  - name: default
    label: ギャラリー01
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - img: 'https://lokeshdhakar.com/projects/lightbox2/images/thumb-1.jpg'
      text: 'Image #1'
    - img: 'https://lokeshdhakar.com/projects/lightbox2/images/thumb-2.jpg'
      text: 'Image #2'
    - img: 'https://lokeshdhakar.com/projects/lightbox2/images/thumb-3.jpg'
      text: 'Image #3'
