title: 利用規約確認
label: 利用規約確認
variants:
  - name: default
    label: 汎用パーツ02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
context:
  link: '#'
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。<br>テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
