title: 汎用パーツ02
label: 汎用パーツ02
variants:
  - name: default
    label: 汎用パーツ02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-utilities'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
