title: カード07
label: カード07
variants:
  - name: default
    label: カード07
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: https://kansou.co.jp/wp2020/wp-content/uploads/2020/09/main_d-680x680.png
  date: 2021.01.01
  title: タイトルが入ります。タイトルが入ります。
