title: スクロールアニメーション04
label: スクロールアニメーション04
variants:
  - name: default
    label: スクロールアニメーション04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  img: 'https://picsum.photos/id/237/300/200'
