title: カード18
label: カード18
variants:
  - name: default
    label: カード18
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  num: '01'
  title: 'タイトルが入ります'
  titleEn: 'English title'
  img: 'https://picsum.photos/id/1000/600/200'
