title: コンテンツ01
label: コンテンツ01
variants:
  - name: default
    label: コンテンツ01
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
  list:
    - '項目1'
    - '項目2'
    - '項目3'
  tableRows:
    -
      - 'テーブル項目1-1'
      - 'テーブル項目1-2'
      - 'テーブル項目1-3'
    -
      - 'テーブル項目2-1'
      - 'テーブル項目2-2'
      - 'テーブル項目2-3'