title: カード13
label: カード13
variants:
  - name: default
    label: カード13
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: 'https://www.themeum.com/wp-content/uploads/2020/11/docent.jpg'
