title: カード02
label: カード02
variants:
  - name: default
    label: カード02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  tag: 'タグが入ります'
  img: 'http://placehold.jp/350x350.png?text=ICON'
  width: 350
  height: 350
  heading: '見出しが入ります'
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
