title: カード17
label: カード17
variants:
  - name: default
    label: カード17
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://picsum.photos/id/1000/400/400'
  date: '2021-00-00'
  title: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
  tag: 'CATEGORY'
