title: スクリーンリーダー調査（テーブルデータ）
label: スクリーンリーダー調査（テーブルデータ）
variants:
  - name: default
    label: スクリーンリーダー調査（テーブルデータ）
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-accessibility'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
