title: 入力制限
label: 入力制限
variants:
  - name: default
preview: '@preview-utilities'
status: ready
# status: prototype
# status: wip
# hidden: true
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
