title: 開始アニメーション02
label: 開始アニメーション02
variants:
  - name: default
    label: 開始アニメーション02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - img: 'https://picsum.photos/id/1000/1200/600'
    - img: 'https://picsum.photos/id/1001/1200/600'
    - img: 'https://picsum.photos/id/1002/1200/600'
    - img: 'https://picsum.photos/id/1003/1200/600'
    - img: 'https://picsum.photos/id/1004/1200/600'
    - img: 'https://picsum.photos/id/1005/1200/600'
    - img: 'https://picsum.photos/id/1006/1200/600'
    - img: 'https://picsum.photos/id/1008/1200/600'
    - img: 'https://picsum.photos/id/1009/1200/600'
    - img: 'https://picsum.photos/id/1010/1200/600'
