title: カルーセル02
label: カルーセル02
variants:
  - name: default
    label: カルーセル02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  items:
    - link: '#'
      img: 'https://picsum.photos/id/1001/400/400'
      width: 400
      height: 400
      date: '2021/01/01'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      img: 'https://picsum.photos/id/1002/400/400'
      width: 400
      height: 400
      date: '2021/01/02'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      img: 'https://picsum.photos/id/1003/400/400'
      width: 400
      height: 400
      date: '2021/01/03'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      img: 'https://picsum.photos/id/1004/400/400'
      width: 400
      height: 400
      date: '2021/01/04'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - link: '#'
      img: 'https://picsum.photos/id/1005/400/400'
      width: 400
      height: 400
      date: '2021/01/05'
      text: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
