title: スクロールアニメーション06
label: スクロールアニメーション06
variants:
  - name: default
    label: スクロールアニメーション06
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
preview: '@preview-scroll'
context:
  items:
    - 'テキストが入ります。テキストが入ります。テキストが入ります。'
    - 'テキストが入ります。テキストが入ります。テキストが入ります。'
    - 'テキストが入ります。テキストが入ります。テキストが入ります。'
