title: よくある質問03
label: よくある質問03
variants:
  - name: default
    label: よくある質問03
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  faqItems:
    - num: '1'
      question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - num: '2'
      question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
    - num: '3'
      question: '質問が入ります。'
      answer: 'テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。テキストが入ります。'
