title: その他03
label: その他03
variants:
  - name: default
    label: その他03
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: 'https://picsum.photos/800/400'
