title: その他02
label: その他02
variants:
  - name: default
    label: その他02
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  headingEn: 'OTHER 02'
  heading: 'その他 02'
