title: その他14
label: その他14
variants:
  - name: default
    label: その他14
    # status: ready
    # status: prototype
    status: wip
hidden: true
context:
  controls:
    - name: 'play'
      label: '再生'
    - name: 'stop'
      label: '停止'
    - name: 'pause'
      label: '一時停止'
    # - name: 'goToAndPlay'
    #   label: '指定位置から開始'
