title: その他29
label: その他29
variants:
  - name: default
    label: その他29
    status: ready
    # status: prototype
    # status: wip
# hidden: true
context:
  src: 'https://picsum.photos/id/134/800/450'
