title: アクセシビリティ01
label: アクセシビリティ01
variants:
  - name: default
    label: アクセシビリティ01
    status: ready
    # status: prototype
    # status: wip
    hidden: true
preview: '@preview-accessibility'
# context:
#   text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
