title: その他04
label: その他04
variants:
  - name: default
    label: その他04
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  subText: 'Other04'
  text: 'This is heading text'
