title: カード05
label: カード05
variants:
  - name: default
    label: カード05
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  img: https://picsum.photos/400/200
