title: ボタン25
label: ボタン25
variants:
  - name: default
    label: ボタン25
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  text: 'BUTTON25'
