title: ボタン16
label: ボタン16
variants:
  - name: default
    label: ボタン16
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  text: 'BUTTON16'
