title: スクロールアニメーション31
label: スクロールアニメーション31
variants:
  - name: default
    label: スクロールアニメーション31
    status: ready
    # status: prototype
    # status: wip
hidden: true
preview: '@preview-scroll'
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
