title: スクロールアニメーション30
label: スクロールアニメーション30
variants:
  - name: default
    label: スクロールアニメーション30
    status: ready
    # status: prototype
    # status: wip
# hidden: true
preview: '@preview-scroll'
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
