title: その他13
label: その他13
variants:
  - name: default
    label: その他13
    status: ready
# preview: '@preview-utilities'
    # status: prototype
    # status: wip
    # hidden: true
context:
  text: 'テキストが入ります。テキストが入ります。テキストが入ります。'
