title: カード01
label: カード01
variants:
  - name: default
    label: カード01
    status: ready
    # status: prototype
    # status: wip
    # hidden: true
context:
  link: '#'
  img: 'https://picsum.photos/400/200'
  title: 'カード01'
  titleEn: 'CARD01'
